// specs/technical/client-app/code/AuthCallback.svelte
<!-- src/routes/AuthCallback.svelte -->
<script lang="ts">
  import { onMount } from 'svelte';
  import { push } from 'svelte-spa-router';
  import { authService } from '../lib/auth/oauth';

  let error: string | null = null;

  onMount(async () => {
    const urlParams = new URLSearchParams(window.location.search);
    const code = urlParams.get('code');
    const errorParam = urlParams.get('error');

    if (errorParam) {
      error = 'Authentication failed';
      return;
    }

    if (!code) {
      error = 'No authorization code received';
      return;
    }

    try {
      await authService.handleCallback(code);
      push('/'); // Redirect to home
    } catch (err) {
      error = err.message;
    }
  });
</script>

{#if error}
  <div class="error">
    <p>{error}</p>
    <a href="/login">Back to login</a>
  </div>
{:else}
  <div class="loading">
    <p>Completing sign in...</p>
  </div>
{/if}

<style>
  .error, .loading {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    min-height: 100vh;
    text-align: center;
  }

  .error {
    color: #d32f2f;
  }
</style>

// specs/technical/client-app/code/AuthCallback.vue
<!-- src/routes/AuthCallback.vue -->
<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { useRouter } from 'vue-router';
import { authService } from '../lib/auth/oauth';

const router = useRouter();
const error = ref<string | null>(null);

onMounted(async () => {
  const urlParams = new URLSearchParams(window.location.search);
  const code = urlParams.get('code');
  const errorParam = urlParams.get('error');

  if (errorParam) {
    error.value = 'Authentication failed';
    return;
  }

  if (!code) {
    error.value = 'No authorization code received';
    return;
  }

  try {
    await authService.handleCallback(code);
    router.push('/'); // Redirect to home
  } catch (err) {
    error.value = err instanceof Error ? err.message : 'An error occurred';
  }
});
</script>

<template>
  <div v-if="error" class="error">
    <p>{{ error }}</p>
    <router-link to="/login">Back to login</router-link>
  </div>
  <div v-else class="loading">
    <p>Completing sign in...</p>
  </div>
</template>

<style scoped>
.error, .loading {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  min-height: 100vh;
  text-align: center;
}

.error {
  color: #d32f2f;
}
</style>
